Fix for @Default ignored for "contract-first" style controller (#793)
Given an interface with a @Default on a @QueryParam like:
```java
@QueryParam("useMaster") @Default("false") boolean useMaster
```
The `@Default("false")` was not being read and applied on the query parameter. This resulted in a null being used and a InvalidPathArgumentException.

```
io.avaje.http.api.InvalidPathArgumentException: path element is null
 at io.avaje.http.api.PathTypeConversion.checkNull(PathTypeConversion.java:52)
 at io.avaje.http.api.PathTypeConversion.asBoolean(PathTypeConversion.java:178)
 at io.avaje.http.api.PathTypeConversion.asBool(PathTypeConversion.java:186)
 ...
```

The fix has 2 parts:
A) Improve ProcessingContext.superMethods() which only matched on name and instead match also on parameter types etc
B) Fix MethodReader to use the annotated element [from the super method / interface] as the controller method itself does not have those annotations like @Default.

Co-authored-by: robin.bygrave <robin.bygrave@eroad.com>